---

- name: Interfaces | Debian | Copy new interfaces file to source interfaces.d
  copy:
    src: interfaces
    dest: /etc/network/interfaces
    owner: root
    group: root
    mode: 0644

- name: Interfaces | Debian | Create the directory for interface cfg files
  file:
    path: '{{ interfaces_net_path[ansible_os_family|lower] }}'
    state: directory

