---
- name: Create the network configuration file for ethernet devices
  template:
    src: "ethernet_{{ ansible_os_family|lower }}.j2"
    dest: "{{ interfaces_net_path[ansible_os_family|lower] }}/ifcfg-{{ item.device }}"
  with_items: network_ether_interfaces
  register: ether_result
  notify: restart networking

- shell: 'ifdown {{ item.item.device }}; ifup {{ item.item.device }}'
  with_items: ether_result.results
  when: ether_result is defined and item.changed

